name: Generate Gradle Wrapper


on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Gradle (if not present)
        run: sudo apt install gradle -y

      - name: Generate gradle wrapper
        run: gradle wrapper

      - name: Upload wrapper as artifact
        uses: actions/upload-artifact@v4
        with:
          name: gradle-wrapper
          path: gradle/wrapper/gradle-wrapper.jar
